---
title: "Tutorial 2"
author: "Claudeon Susanto"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import}
library(stringr)
library(rebus)
library(dplyr)
fnames <- list.files("../data/ieer", pattern="^[^R]", full.names=TRUE)
```
## Question 1
Extracting the basename of the files
```{r}
basename1 <- sapply(str_split(fnames,"/"), function(x) x[4])
basename2 <- str_sub(fnames,14)
dir <- sapply(str_split(fnames,"/"), function(x) c(x[3],x[4]))
str_extract(fnames, "[^/]+$")
```

## Question 2
Extracting files written in April
```{r}
apr_files1 <- str_subset(basename1,"[\\d]{4}04[\\d]{2}")
```

## Question 3
```{r}
file1 <- readLines(fnames[1])
start_end <- str_which(file1, "</?DOC>")
start_end
```

## Question 4
### 4(a)
```{r}
str_trim(str_replace_all(str_subset(file1, "<DOCNO>"), or("<DOCNO>", "</DOCNO>"), ""))
```
### 4(b)
```{r}
date_strings <- str_trim(str_remove_all(str_subset(file1, "(?<=DATE_TIME> )([\\S ]+)(?= +</DATE_TIME>$)"), "</?DATE_TIME>"))
# str_extract(file1, "(?<=DATE_TIME> )([0-9/: ]+)(?= +</DATE_TIME>$)")

date_strings
```
## Question 5

```{r}
pattern <- "^([0-9]{2})/([0-9]{2})"
str_extract(date_strings, pattern)
str_replace(date_strings, pattern, "\\2/\\1")
```

## Question 6



## Question 7


## Question 8
```{r}
text_start <- str_which(file1, "<TEXT>")
text_end <- str_which(file1, "</TEXT>")
file1_cleaned <- str_remove_all(file1, "<[^>]+>")
# paste(file1_cleaned, sep=" ", collapse="")
```














