---
title: "Tutorial 8"
author: "Claudeon Susanto"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
```{r}
wdbc <- read.delim("../data/wdbc.data", header=FALSE, sep=",") %>% select(1:12)
colnames(wdbc) <- c("id", "diagnosis", "radius", "texture", "perimeter", "area",
                    "smoothness", "compactness", "concavity", "concave.pts",
                    "symmetry", "fractal.dim")
```
## Histogram of radius 
```{r}
wdbc %>% 
  mutate(diagnosis = recode(diagnosis, B = "Benign", M = "Malignant")) %>%
  ggplot(aes(x=radius,y=after_stat(density),fill=diagnosis)) + 
  geom_histogram(position="dodge", color="lightgrey",bins=30) + 
  labs(title="Distribution of Radius by Diagnosis", x="Radius", y="Density") + 
  geom_density(aes(color=diagnosis,fill=NULL))
wdbc %>% 
  ggplot(aes(x=radius, y=after_stat(density))) + 
  geom_density(aes(color=diagnosis)) +
  geom_histogram(aes(fill=diagnosis)) + 
  facet_wrap(~diagnosis,nrow=2)
wdbc %>%
  ggplot(aes(x=radius,fill=diagnosis)) +
  geom_histogram(alpha=0.5, position="identity")
```

## Proportion of Benign Cancer
```{r}
wdbc %>%
  mutate(radius.interval = cut_interval(radius,length=2)) %>%
  group_by(radius.interval) %>%
  summarise(proportion.benign = mean(diagnosis=="B"), count=n(), ymin = proportion.benign - 1.96*sqrt(proportion.benign*(1-proportion.benign)/count), ymax=proportion.benign + 1.96*sqrt(proportion.benign*(1-proportion.benign)/count)) %>%
  ggplot() +
  geom_point(aes(x=radius.interval, y=proportion.benign)) + 
  geom_line(aes(x=radius.interval,y=proportion.benign),group=TRUE) + 
  geom_errorbar(aes(x=radius.interval, ymin=ymin,ymax=ymax)) +
  labs(title="Proportion of Benign Diagnosis falls as Radius increases", x="Radius intervals", y="Proportion of Benign cases")
wdbc %>%
  mutate(radius.interval = cut_interval(radius,length=2), symmetry.interval = cut_number(symmetry,2)) %>%
  group_by(radius.interval, symmetry.interval) %>%
  summarise(proportion.benign = mean(diagnosis=="B")) %>%
  ggplot(aes(color=symmetry.interval)) +
  geom_point(aes(x=radius.interval, y=proportion.benign)) + 
  geom_line(aes(x=radius.interval,y=proportion.benign,group=symmetry.interval),)
```

## Data Exploration
```{r}
wdbc %>%
  ggplot() +
  geom_boxplot(aes(x=diagnosis, y=radius, linetype='drv'))
wdbc %>%
  ggplot(aes(x=area, y=smoothness, color=diagnosis)) +
  geom_point(position="jitter") + 
  geom_smooth(span=10, color="black" ) + 
  facet_wrap(~diagnosis,nrow=2)
wdbc %>%
  ggplot(aes(x=radius, fill=diagnosis)) +
  geom_histogram()+
  facet_wrap(~diagnosis)
```